name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aiken-lang/setup-aiken@v1
        with:
          version: v1.1.24
      - run: aiken fmt --check
      - run: aiken check -D
      - run: aiken build

  offchain:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: offchain
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm test
